version: '3'

services:
  jenkins:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DOCKER_HOST=tcp://socat:2375

  socat:
    image: bpack/socat
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "2375"
